### PR TITLE
changes from https://code.google.com/p/selenium/source/detail?r=8c3c6577...

### PR DESCRIPTION
**Pull request by voodoo144**
Now POST to /session doesn't redirect to /session/:sessionId url, it now return sessionId value in json response.

### CODE REVIEW

**Comment by voodoo144** [comment]
> @@ -56,8 +56,8 @@ public function session($browser = 'firefox',
>        '/session',
>        array('desiredCapabilities' => $desired_capabilities),
>        $curl_opts);
> -    // var_dump($results);
> -    return new PHPWebDriver_WebDriverSession($results['info']['url']);
> -      //var_dump($results);
> -    return new PHPWebDriver_WebDriverSession($results['info']['url'].$results['sessionId']);

I test this code with GhostDriver 1.0.4, when I write it Selenium 2.34 was still unreleased.

**Comment by jvanbouchaute** [comment]
+1. Breaks compatibility with Selenium 2.35

**Comment by adamgoucher** [comment]
I'll look at this tonight

**Comment by jvanbouchaute** [comment]
Thanks !
Op 20-aug.-2013 12:29 schreef "adam goucher" notifications@github.com het
volgende:

**Comment by voodoo144** [comment]
thanks a lot )

**Pull request merged**
